export const ActionTypes = {
  SET_ITEMS: 'SET_ITEMS',
  SET_ITEMS_BY_NAME: 'SET_ITEMS_BY_NAME',
  SET_ITEMS_BY_FULL_NAME: 'SET_ITEMS_BY_FULL_NAME',
  SET_ITEMS_BY_CODE: 'SET_ITEMS_BY_CODE',
  SET_ITEMS_BY_CODE_LIST: 'SET_ITEMS_BY_CODE_LIST',
  SET_BY_CURRENCY: 'SET_BY_CURRENCY',
  SET_BY_LANGUAGE: 'SET_BY_LANGUAGE',
  SET_BY_CAPITAL: 'SET_BY_CAPITAL',
  SET_ERROR: 'SET_ERROR',
};

export default ActionTypes;
