export const ActionTypes = {
  SET_ITEMS: 'SET_ITEMS',
  SET_ITEMS_BY_NAME: 'SET_ITEMS_BY_NAME',
  SET_ITEMS_BY_FULL_NAME: 'SET_ITEMS_BY_FULL_NAME',
  SET_ITEMS_BY_CODE: 'SET_ITEMS_BY_CODE',
  SET_ITEMS_BY_CODE_LIST: 'SET_ITEMS_BY_CODE_LIST',
  SET_ERROR: 'SET_ERROR',
};

export default ActionTypes;
